### ISSUE TITLE
Crash when navigate to the course directly

### ISSUE THREAD

**Issue by Chensokheng** [Chensokheng/react-course-theme#1]
The reason is every route is connected. So the data is pass from one route to another. to solve that we need to fetch data if the data is null (not being pass from another).

**Comment by lixiaoqity** [comment]
I will try to fix it.

**Comment by lixiaoqity** [comment]
I have fixed it. Please see the pull request.

**Comment by Chensokheng** [comment]
@lixiaoqity Thank you for making your PR. I have checked it. Everything is fine. But can you fixed the CourseSession route as well. https://react-course-theme.netlify.app/course/React%20for%20beginner/Introduction. Then I will close this issue. It is the same problem but different route.

**Comment by lixiaoqity** [comment]
> @lixiaoqity Thank you for making your PR. I have checked it. Everything is fine. But can you fixed the CourseSession route as well. https://react-course-theme.netlify.app/course/React%20for%20beginner/Introduction. Then I will close this issue. It is the same problem but different route.

I've done it. Please see the pull request. Thank you.
